var $jscomp={scope:{},owns:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var f=arguments[b];if(f)for(var g in f)$jscomp.owns(f,g)&&(a[g]=f[g])}return a}},"es6-impl","es3");
function Anima(a){var b=this;this.skeleton=new Skeleton(a.skeleton);this.motion=[];a.motion.forEach(function(a){var d=[];a.forEach(function(a,c){var e=Matrix.NO_EFFECT;if(null!=a){var f=Matrix.rotateX(a[0]),g=Matrix.rotateY(a[1]),m=Matrix.rotateZ(a[2]);b.skeleton.list[c].order.split("").forEach(function(a){"x"==a?e=e.multiply(f):"y"==a?e=e.multiply(g):"z"==a&&(e=e.multiply(m))})}var l={rotate:e};null!=a&&3<a.length&&(l.tx=a[3],l.ty=a[4],l.tz=a[5]);d.push(l)});b.motion.push(d)})}
Anima.prototype.rotateH=function(a){this.skeleton.rotationH=a;this.skeleton.calcRotationMatrix()};Anima.prototype.rotateV=function(a){this.skeleton.rotationV=a;this.skeleton.calcRotationMatrix()};Anima.prototype.shift=function(a,b){this.skeleton.shift(this.motion[a%this.motion.length],b)};Anima.prototype.calculate=function(a){this.skeleton.calculate(a)};Anima.prototype.draw=function(a){this.skeleton.draw(a)};
function AudioMixer(){Repository.apply(this,arguments);this.type="arraybuffer";this.ctx=null;if(window.AudioContext||window.webkitAudioContext)this.ctx=new (window.AudioContext||window.webkitAudioContext);this.dic=[];this.bgm=[];this.lastTime=this.lastKey=null}AudioMixer.prototype=Object.create(Repository.prototype);AudioMixer.INSTANCE=new AudioMixer;AudioMixer.prototype.makeName=function(a){return-1!==navigator.userAgent.toLowerCase().indexOf("edge")?"audio/"+a+".mp3":"audio/"+a+".webm"};
AudioMixer.prototype.onload=function(a,b,c){var d=this;null===this.ctx?this.done():this.ctx.decodeAudioData(c,function(b){d.dic[a]=b;d.done()})};
AudioMixer.prototype.play=function(a){if(null!==this.ctx&&this.dic[a]){var b=arguments.length,c=1<b?arguments[1]:1,d=2<b?arguments[2]:!1,f=3<b?arguments[3]:0,b=4<b?arguments[4]:0,g=this.dic[a],e=new AudioElement(this.ctx,g,b);d&&(e.source.loopEnd=g.duration+10,e.source.loop=!1,this.bgm.push(e),this.lastKey=a);e.gainNode.gain.value=c;e.setPan(f);this.lastTime=this.ctx.currentTime-b}};AudioMixer.prototype.setPan=function(a){this.bgm.forEach(function(b){b.setPan(a)})};
AudioMixer.prototype.fade=function(){console.log("fade:");this.bgm.forEach(function(a){a.fade()})};AudioMixer.prototype.stop=function(){console.log("stop:");this.bgm.forEach(function(a){a.stop()})};AudioMixer.prototype.getCurrentTime=function(){if(0<this.bgm.length){var a=[];this.bgm.forEach(function(b){b.done||a.push(b)});this.bgm=a}return this.bgm.length?this.ctx.currentTime-this.lastTime:null};
AudioMixer.prototype.setCurrentTime=function(a){this.bgm.length&&(this.stop(),this.play(this.lastKey,1,!0,0,a))};
function AudioElement(a,b,c){var d=this;this.done=!1;this.source=a.createBufferSource();this.gainNode=a.createGain();this.gainNode.connect(a.destination);"function"==typeof a.createStereoPanner?(this.panNode=a.createStereoPanner(),this.panNode.connect(this.gainNode),this.source.connect(this.panNode)):(this.panNode=null,this.source.connect(this.gainNode));this.source.buffer=b;this.source.start(0,c);this.source.onended=function(){console.log("onended.");d.done=!0}}
AudioElement.prototype.setPan=function(a){this.panNode&&(this.panNode.pan.value=a)};AudioElement.prototype.fade=function(){var a=this,b=this.gainNode.gain,c=b.value,d=function(){0==Math.floor(100*c)?a.stop():(c*=.7,b.value=c,setTimeout(d,100))};d()};AudioElement.prototype.stop=function(){this.done||this.source.stop()};function Field(){this.motionNo=0;this.rotationH=Field.DEFAULT_H;this.rotationV=Math.PI/8;this.animaList=[];this.init()}Field.WIDTH=960;Field.HEIGHT=540;Field.DEFAULT_H=155*Math.PI/180;
Field.COLOR_LIST=["lightpink","palegreen","lightskyblue","orange"];Field.prototype.init=function(){this.ctx=document.getElementById("canvas").getContext("2d")};Field.prototype.resetCanvas=function(a,b){this.width=a;this.height=b;this.hW=this.width/2;this.hH=this.height/2;this.scale=a/Field.WIDTH/2;$("#canvas").attr("width",this.width).attr("height",this.height)};
Field.prototype.addMotion=function(a){var b=$("#slider");console.log("motions:"+a.motion.length);this.animaList.push(new Anima(a));this.resetMotion();b.prop("max",a.motion.length-1);b.slider("refresh")};Field.prototype.loadMotion=function(a){var b=this,c=$("#slider");b.shiftMotion(0);c.val(0).slider("refresh");return $.ajax("dat/"+a,{dataType:"json",success:function(a){b.addMotion(a)}})};Field.prototype.resetMotion=function(){this.shiftMotion(0);this.rotateH(0);this.rotateV(0);this.draw()};
Field.prototype.shiftMotion=function(a){for(var b=this,c=a<this.motionNo?-1:1;this.motionNo!=a;)0<c&&(this.motionNo+=c),this.animaList.forEach(function(d){d.shift(b.motionNo,c);d.calculate(b.motionNo!=a)}),0>c&&(this.motionNo+=c)};Field.prototype.nextMotion=function(a){a=this.motionNo;a++;this.shiftMotion(a)};Field.prototype.rotateH=function(a){var b=this;this.rotationH+=Math.PI/720*a;this.rotationH=Math.trim(this.rotationH);this.animaList.forEach(function(a){a.rotateH(b.rotationH)});AudioMixer.INSTANCE.setPan(this.getPanValue())};
Field.prototype.getPanValue=function(){return Math.sin(this.rotationH-Field.DEFAULT_H)};Field.prototype.rotateV=function(a){var b=this;this.rotationV+=Math.PI/720*a;this.rotationV=Math.trim(this.rotationV);this.animaList.forEach(function(a){a.rotateV(b.rotationV)})};
Field.prototype.draw=function(){var a=this.ctx,b=Field.COLOR_LIST.length;a.clearRect(0,0,this.width,this.height);a.save();a.strokeStyle="rgba(255, 255, 255, .7)";a.strokeText("H:"+Math.floor(180*this.rotationH/Math.PI),2,20);a.strokeText("V:"+Math.floor(180*this.rotationV/Math.PI),2,30);a.strokeText("m:"+this.motionNo,2,40);a.translate(this.hW,this.hH);a.scale(this.scale,this.scale);a.lineCap="round";this.animaList.forEach(function(c,d){a.strokeStyle=Field.COLOR_LIST[d%b];c.draw(a)});a.restore()};
Math.PI2=Math.PI2||2*Math.PI;Math.SQ=Math.SQ||Math.PI/2;Math.trim=Math.trim||function(a){for(;Math.PI<a;)a-=Math.PI2;for(;a<-Math.PI;)a+=Math.PI2;return a};Math.close=Math.close||function(a,b,c){b=Math.trim(a-b);return Math.abs(b)<=c?a:0<b?a-c:a+c};function Matrix(a){this.mat=a}Matrix.NO_EFFECT=new Matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]);Matrix.rotateX=function(a){return new Matrix([[1,0,0,0],[0,Math.cos(a),-Math.sin(a),0],[0,Math.sin(a),Math.cos(a),0],[0,0,0,1]])};
Matrix.rotateY=function(a){return new Matrix([[Math.cos(a),0,Math.sin(a),0],[0,1,0,0],[-Math.sin(a),0,Math.cos(a),0],[0,0,0,1]])};Matrix.rotateZ=function(a){return new Matrix([[Math.cos(a),-Math.sin(a),0,0],[Math.sin(a),Math.cos(a),0,0],[0,0,1,0],[0,0,0,1]])};Matrix.prototype.multiply=function(a){var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=a.mat;this.mat.forEach(function(a,f){a.forEach(function(d,e){for(var g=0,h=0;4>h;h++)g+=a[h]*c[h][e];b[f][e]=g})});return new Matrix(b)};
Matrix.prototype.affine=function(a,b,c){var d=this.mat;return{x:d[0][0]*a+d[0][1]*b+d[0][2]*c+d[0][3],y:d[1][0]*a+d[1][1]*b+d[1][2]*c+d[1][3],z:d[2][0]*a+d[2][1]*b+d[2][2]*c+d[2][3]}};function MotionManager(){Repository.apply(this,arguments)}MotionManager.prototype=Object.create(Repository.prototype);MotionManager.INSTANCE=new MotionManager;MotionManager.prototype.makeName=function(a){return"motion/"+a+".json"};
function Repository(){this.loaded=this.max=0;this.dic={};this.reserved={};this.type="json"}Repository.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};Repository.prototype.reserve=function(a){var b=this;a.forEach(function(a){null==a||a in b.reserved||(b.reserved[a]=!0,b.load(a))})};Repository.prototype.makeName=function(a){return a};
Repository.prototype.load=function(a){var b=this,c=new XMLHttpRequest,d=this.makeName(a);this.max++;c.open("GET",d,!0);c.responseType=this.type;c.addEventListener("loadend",function(){var f=c.response;b.dic[a]=f;b.onload(a,d,f)});c.send()};Repository.prototype.onload=function(a,b,c){this.done()};Repository.prototype.done=function(){this.loaded++};
function Skeleton(a){this.data=a;this.calcOrder="RotateTranslate"==this.data.calcOrder?0:1;this.list=[];this.map={};this.offsetY=this.offsetX=0;this.scale=a.scale;this.rotationH=Math.PI/4;this.rotationV=Math.PI/8;this.rotationMatrix=Matrix.NO_EFFECT;this.init()}Skeleton.prototype.init=function(){var a=Object.assign(new Bone,this.data.root);this.data.root=a;this.prepare(a);this.calcRotationMatrix()};
Skeleton.prototype.prepare=function(a){var b=this,c=[];this.list.push(a);a.prepare();a.joint.forEach(function(b){b.parent=a;c.push(Object.assign(new Bone,b))});a.joint=c;a.joint.forEach(function(a){b.prepare(a)});a.skeleton=this;this.map[a.name]=a};Skeleton.prototype.calcRotationMatrix=function(){var a=Matrix.rotateY(this.rotationH);this.rotationMatrix=Matrix.rotateX(this.rotationV).multiply(a)};
Skeleton.prototype.shift=function(a,b){var c=this;a.forEach(function(a,f){var d=c.list[f];d.motionMatrix=a.rotate;if(a.tx){var e=d.pt;d.translateMatrix=new Matrix([[1,0,0,c.offsetX+e.x+a.tx*b],[0,1,0,c.offsetY+e.y+a.ty*b],[0,0,1,e.z+a.tz*b],[0,0,0,1]])}})};Skeleton.prototype.calculate=function(a){this.data.root.calculate(a)};Skeleton.prototype.draw=function(a){a.save();a.lineWidth=8;this.data.root.draw(a);a.restore()};function Bone(){this.pt={x:0,y:0,z:0}}
Bone.prototype.prepare=function(){var a=this.translate,b=Matrix.rotateX(this.axis.x),c=Matrix.rotateY(this.axis.y),b=Matrix.rotateZ(this.axis.z).multiply(c).multiply(b);this.translateMatrix=new Matrix([[1,0,0,a.x],[0,1,0,a.y],[0,0,1,a.z],[0,0,0,1]]);if(this.parent){var d=this.parent,a=Matrix.rotateX(-d.axis.x),c=Matrix.rotateY(-d.axis.y),d=Matrix.rotateZ(-d.axis.z);this.axisMatrix=a.multiply(c).multiply(d).multiply(b)}else this.axisMatrix=b;this.motionMatrix=Matrix.NO_EFFECT};
Bone.prototype.getAccum=function(){var a=this.skeleton.calcOrder;return this.parent?(a=0==a?this.axisMatrix.multiply(this.motionMatrix).multiply(this.translateMatrix):this.axisMatrix.multiply(this.translateMatrix).multiply(this.motionMatrix),this.parent.getAccum().multiply(a)):this.translateMatrix.multiply(this.motionMatrix)};Bone.prototype.calculate=function(a){this.pt=this.getAccum().affine(0,0,0);a||this.joint.forEach(function(a){a.calculate(!1)})};
Bone.prototype.conv=function(a){a=this.skeleton.rotationMatrix.affine(a.x,a.y,a.z);var b=(a.z+2E3)/2E3;return(new Matrix([[b,0,0,0],[0,b,0,0],[0,0,b,0],[0,0,0,1]])).affine(a.x,a.y,a.z)};Bone.prototype.drawLine=function(a){var b=this.conv(this.parent.pt),c=this.conv(this.pt),d=this.skeleton.scale,f=c.x*d,g=-c.y*d,e=b.x*d,b=-b.y*d,d=f-e,k=g-b;this.cx=e+d/2;this.cy=b+k/2;this.cz=c.z;this.radian=Math.atan2(k,d);a.beginPath();a.moveTo(e,b);a.lineTo(f,g);a.stroke()};
Bone.prototype.draw=function(a){this.calculate();this.parent&&this.drawLine(a);this.joint.forEach(function(b){b.draw(a)})};
document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("loading"),b=[AudioMixer.INSTANCE,MotionManager.INSTANCE],c=["aachan.bvh","kashiyuka.bvh","nocchi.bvh"],d=$("#view"),f=$("#slider"),g=!1,e=new Field,k=0,h=0,m=0,l=function(a){if(a.type.match(/^mouse/))k=a.pageX,h=a.pageY;else if(a.originalEvent.touches){var b=a.originalEvent.touches[0];k=b.pageX;h=b.pageY}m=a.which},p=function(a){var b,c;if(a.type.match(/^mouse/)){if(!m)return;b=a.pageX;c=a.pageY}else a.originalEvent.touches&&
(c=a.originalEvent.touches[0],b=c.pageX,c=c.pageY);a=h-c;e.rotateH(k-b);e.rotateV(a);k=b;h=c},n=function(a){m=0},q=function(){var a=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame,b=AudioMixer.INSTANCE.getCurrentTime();b&&(b=parseInt(b/.025),e.shiftMotion(b),g=!0,f.val(b),f.slider("refresh"),g=!1);e.draw();a(q)};d.mousedown(l);d.mousemove(p);d.mouseleave(n);d.mouseup(n);d.bind("touchstart",l);d.bind("touchmove",p);d.bind("touchend",
n);f.change(function(){if(!g){var a=$(this).val(),b=.025*a;e.shiftMotion(a);AudioMixer.INSTANCE.setCurrentTime(b)}});$(window).resize(function(){var a=$("body"),b=$("#header"),c=$("#footer"),d=a.width(),a=a.height()-b.outerHeight(!0)-c.outerHeight(!0)-16;a/9<d/16?d=parseInt(a/9*16):a=parseInt(d/16*9);e.resetCanvas(d,a)});$(window).resize();$("#playButton").click(function(){if(AudioMixer.INSTANCE.getCurrentTime())AudioMixer.INSTANCE.fade();else{var a=e.getPanValue(),b=f.val();AudioMixer.INSTANCE.play("Perfume_globalsite_sound",
1,!0,a,.025*b)}});MotionManager.INSTANCE.reserve(c);AudioMixer.INSTANCE.reserve(["Perfume_globalsite_sound"]);var r=function(){var d=0,f=0,g=!0;b.forEach(function(a){d+=a.loaded;f+=a.max;g&=a.isComplete()});a.innerHTML=d+"/"+f;g?($.mobile.loading("hide"),a.parentNode.removeChild(a),q(),c.forEach(function(a){e.addMotion(MotionManager.INSTANCE.dic[a])})):setTimeout(r,100)};$.mobile.loading("show",{textVisible:!0});r()});
