var $jscomp={scope:{},owns:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,d){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)$jscomp.owns(e,f)&&(a[f]=e[f])}return a}},"es6-impl","es3");
var Anima=function(a){var b=this;this.skeleton=new Skeleton(a.skeleton);this.name="";this.motion=[];a.motion.forEach(function(a){var c=[];a.forEach(function(a,d){var e=Matrix.NO_EFFECT;if(null!=a){var f=Matrix.rotateX(a[0]),k=Matrix.rotateY(a[1]),m=Matrix.rotateZ(a[2]);b.skeleton.list[d].order.split("").forEach(function(a){"x"==a?e=e.multiply(f):"y"==a?e=e.multiply(k):"z"==a&&(e=e.multiply(m))})}var l={rotate:e};null!=a&&3<a.length&&(l.tx=a[3],l.ty=a[4],l.tz=a[5]);c.push(l)});b.motion.push(c)})};
Anima.prototype.getHead=function(){return this.skeleton.map.head};Anima.prototype.rotateH=function(a){this.skeleton.rotationH=a;this.skeleton.calcRotationMatrix()};Anima.prototype.rotateV=function(a){this.skeleton.rotationV=a;this.skeleton.calcRotationMatrix()};Anima.prototype.shift=function(a,b){this.skeleton.shift(this.motion[a%this.motion.length],b)};Anima.prototype.calculate=function(a){this.skeleton.calculate(a)};Anima.prototype.draw=function(a){this.skeleton.draw(a)};
function AudioMixer(){Repository.apply(this,arguments);this.type="arraybuffer";this.ctx=null;if(window.AudioContext||window.webkitAudioContext)this.ctx=new (window.AudioContext||window.webkitAudioContext);this.dic=[];this.bgm=[];this.lastTime=this.lastKey=null}AudioMixer.prototype=Object.create(Repository.prototype);AudioMixer.INSTANCE=new AudioMixer;AudioMixer.prototype.makeName=function(a){return-1!==navigator.userAgent.toLowerCase().indexOf("edge")?"audio/"+a+".mp3":"audio/"+a+".webm"};
AudioMixer.prototype.onload=function(a,b,d){var c=this;null===this.ctx?this.done():this.ctx.decodeAudioData(d,function(b){c.dic[a]=b;c.done()})};
AudioMixer.prototype.play=function(a){if(null!==this.ctx&&this.dic[a]){var b=arguments.length,d=1<b?arguments[1]:1,c=2<b?arguments[2]:!1,e=3<b?arguments[3]:0,b=4<b?arguments[4]:0,f=this.dic[a],g=new AudioElement(this.ctx,f,b);c&&(g.source.loopEnd=f.duration+10,g.source.loop=!1,this.bgm.push(g),this.lastKey=a);g.gainNode.gain.value=d;g.setPan(e);this.lastTime=this.ctx.currentTime-b}};AudioMixer.prototype.setPan=function(a){this.bgm.forEach(function(b){b.setPan(a)})};
AudioMixer.prototype.fade=function(){console.log("fade:");this.bgm.forEach(function(a){a.fade()})};AudioMixer.prototype.stop=function(){console.log("stop:");this.bgm.forEach(function(a){a.stop()})};AudioMixer.prototype.getCurrentTime=function(){if(0<this.bgm.length){var a=[];this.bgm.forEach(function(b){b.done||a.push(b)});this.bgm=a}return this.bgm.length?this.ctx.currentTime-this.lastTime:null};
AudioMixer.prototype.setCurrentTime=function(a){this.bgm.length&&(this.stop(),this.play(this.lastKey,1,!0,0,a))};
function AudioElement(a,b,d){var c=this;this.done=!1;this.source=a.createBufferSource();this.gainNode=a.createGain();this.gainNode.connect(a.destination);"function"==typeof a.createStereoPanner?(this.panNode=a.createStereoPanner(),this.panNode.connect(this.gainNode),this.source.connect(this.panNode)):(this.panNode=null,this.source.connect(this.gainNode));this.source.buffer=b;this.source.start(0,d);this.source.onended=function(){console.log("onended.");c.done=!0}}
AudioElement.prototype.setPan=function(a){this.panNode&&(this.panNode.pan.value=a)};AudioElement.prototype.fade=function(){var a=this,b=this.gainNode.gain,d=b.value,c=function(){0==Math.floor(100*d)?a.stop():(d*=.7,b.value=d,setTimeout(c,100))};c()};AudioElement.prototype.stop=function(){this.done||this.source.stop()};function Field(){this.motionNo=0;this.rotationH=Field.DEFAULT_H;this.rotationV=Math.PI/8;this.animaList=[];this.showName=!1;this.init()}Field.WIDTH=960;Field.HEIGHT=540;
Field.DEFAULT_H=155*Math.PI/180;Field.COLOR_LIST=["lightpink","palegreen","lightskyblue","orange"];Field.prototype.init=function(){this.ctx=document.getElementById("canvas").getContext("2d")};Field.prototype.resetCanvas=function(a,b){this.width=a;this.height=b;this.hW=this.width/2;this.hH=this.height/2;this.scale=a/Field.WIDTH/2;$("#canvas").attr("width",this.width).attr("height",this.height)};
Field.prototype.addMotion=function(a,b){var d=$("#slider"),c=b.motion.length-1,e=parseInt(d.prop("max")),f=new Anima(b);console.log("motions:"+b.motion.length);console.log("max:"+e);f.name=a.split(".")[0];this.animaList.push(f);this.resetMotion();e<c&&d.prop("max",c);d.slider("refresh")};Field.prototype.loadMotion=function(a){var b=this,d=$("#slider");b.shiftMotion(0);d.val(0).slider("refresh");return $.ajax("dat/"+a,{dataType:"json",success:function(c){b.addMotion(a,c)}})};
Field.prototype.resetMotion=function(){this.shiftMotion(0);this.rotateH(0);this.rotateV(0);this.draw()};Field.prototype.shiftMotion=function(a){for(var b=this,d=a<this.motionNo?-1:1;this.motionNo!=a;)0<d&&(this.motionNo+=d),this.animaList.forEach(function(c){c.shift(b.motionNo,d);c.calculate(b.motionNo!=a)}),0>d&&(this.motionNo+=d)};Field.prototype.nextMotion=function(){var a=this.motionNo;a++;this.shiftMotion(a)};
Field.prototype.rotateH=function(a){var b=this;this.rotationH+=Math.PI/720*a;this.rotationH=Math.trim(this.rotationH);this.animaList.forEach(function(a){a.rotateH(b.rotationH)});AudioMixer.INSTANCE.setPan(this.getPanValue())};Field.prototype.getPanValue=function(){return Math.sin(this.rotationH-Field.DEFAULT_H)};Field.prototype.rotateV=function(a){var b=this;this.rotationV+=Math.PI/720*a;this.rotationV=Math.trim(this.rotationV);this.animaList.forEach(function(a){a.rotateV(b.rotationV)})};
Field.prototype.draw=function(){var a=this,b=this.ctx,d=Field.COLOR_LIST.length;b.clearRect(0,0,this.width,this.height);b.save();b.strokeStyle="rgba(255, 255, 255, .7)";b.strokeText("H:"+Math.floor(180*this.rotationH/Math.PI),2,20);b.strokeText("V:"+Math.floor(180*this.rotationV/Math.PI),2,30);b.strokeText("m:"+this.motionNo,2,40);b.translate(this.hW,this.hH);b.scale(this.scale,this.scale);b.lineCap="round";this.animaList.forEach(function(c,e){b.strokeStyle=Field.COLOR_LIST[e%d];c.draw(b);if(a.showName){var f=
c.getHead();b.save();b.font="24px 'Times New Roman'";b.strokeText(c.name,f.cx,f.cy);b.restore()}});b.restore()};Math.PI2=Math.PI2||2*Math.PI;Math.SQ=Math.SQ||Math.PI/2;Math.trim=Math.trim||function(a){for(;Math.PI<a;)a-=Math.PI2;for(;a<-Math.PI;)a+=Math.PI2;return a};Math.close=Math.close||function(a,b,d){b=Math.trim(a-b);return Math.abs(b)<=d?a:0<b?a-d:a+d};function Matrix(a){this.mat=a}Matrix.NO_EFFECT=new Matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]);
Matrix.rotateX=function(a){return new Matrix([[1,0,0,0],[0,Math.cos(a),-Math.sin(a),0],[0,Math.sin(a),Math.cos(a),0],[0,0,0,1]])};Matrix.rotateY=function(a){return new Matrix([[Math.cos(a),0,Math.sin(a),0],[0,1,0,0],[-Math.sin(a),0,Math.cos(a),0],[0,0,0,1]])};Matrix.rotateZ=function(a){return new Matrix([[Math.cos(a),-Math.sin(a),0,0],[Math.sin(a),Math.cos(a),0,0],[0,0,1,0],[0,0,0,1]])};
Matrix.prototype.multiply=function(a){var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],d=a.mat;this.mat.forEach(function(a,e){a.forEach(function(c,g){for(var f=0,k=0;4>k;k++)f+=a[k]*d[k][g];b[e][g]=f})});return new Matrix(b)};Matrix.prototype.affine=function(a,b,d){var c=this.mat;return{x:c[0][0]*a+c[0][1]*b+c[0][2]*d+c[0][3],y:c[1][0]*a+c[1][1]*b+c[1][2]*d+c[1][3],z:c[2][0]*a+c[2][1]*b+c[2][2]*d+c[2][3]}};function MotionManager(){Repository.apply(this,arguments)}MotionManager.prototype=Object.create(Repository.prototype);
MotionManager.INSTANCE=new MotionManager;MotionManager.prototype.makeName=function(a){return"motion/"+a+".json"};function Repository(){this.loaded=this.max=0;this.dic={};this.reserved={};this.type="json"}Repository.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};Repository.prototype.reserve=function(a){var b=this;a.forEach(function(a){null==a||a in b.reserved||(b.reserved[a]=!0,b.load(a))})};Repository.prototype.makeName=function(a){return a};
Repository.prototype.load=function(a){var b=this,d=new XMLHttpRequest,c=this.makeName(a);this.max++;d.open("GET",c,!0);d.responseType=this.type;d.addEventListener("loadend",function(){var e=d.response;b.dic[a]=e;b.onload(a,c,e)});d.send()};Repository.prototype.onload=function(a,b,d){this.done()};Repository.prototype.done=function(){this.loaded++};
function Skeleton(a){this.data=a;this.calcOrder="RotateTranslate"==this.data.calcOrder?0:1;this.list=[];this.map={};this.offsetY=this.offsetX=0;this.scale=a.scale;this.rotationH=Math.PI/4;this.rotationV=Math.PI/8;this.rotationMatrix=Matrix.NO_EFFECT;this.init()}Skeleton.prototype.init=function(){var a=Object.assign(new Bone,this.data.root);this.data.root=a;this.prepare(a);this.calcRotationMatrix()};
Skeleton.prototype.prepare=function(a){var b=this,d=[];this.list.push(a);a.prepare();a.joint.forEach(function(b){b.parent=a;d.push(Object.assign(new Bone,b))});a.joint=d;a.joint.forEach(function(a){b.prepare(a)});a.skeleton=this;this.map[a.name.toLowerCase()]=a};Skeleton.prototype.calcRotationMatrix=function(){var a=Matrix.rotateY(this.rotationH);this.rotationMatrix=Matrix.rotateX(this.rotationV).multiply(a)};
Skeleton.prototype.shift=function(a,b){var d=this;a.forEach(function(a,e){var c=d.list[e];c.motionMatrix=a.rotate;if(a.tx){var g=c.pt;c.translateMatrix=new Matrix([[1,0,0,d.offsetX+g.x+a.tx*b],[0,1,0,d.offsetY+g.y+a.ty*b],[0,0,1,g.z+a.tz*b],[0,0,0,1]])}})};Skeleton.prototype.calculate=function(a){this.data.root.calculate(a)};Skeleton.prototype.draw=function(a){a.save();a.lineWidth=8;this.data.root.draw(a);a.restore()};function Bone(){this.pt={x:0,y:0,z:0}}
Bone.prototype.prepare=function(){var a=this.translate,b=Matrix.rotateX(this.axis.x),d=Matrix.rotateY(this.axis.y),b=Matrix.rotateZ(this.axis.z).multiply(d).multiply(b);this.translateMatrix=new Matrix([[1,0,0,a.x],[0,1,0,a.y],[0,0,1,a.z],[0,0,0,1]]);if(this.parent){var c=this.parent,a=Matrix.rotateX(-c.axis.x),d=Matrix.rotateY(-c.axis.y),c=Matrix.rotateZ(-c.axis.z);this.axisMatrix=a.multiply(d).multiply(c).multiply(b)}else this.axisMatrix=b;this.motionMatrix=Matrix.NO_EFFECT};
Bone.prototype.getAccum=function(){var a=this.skeleton.calcOrder;return this.parent?(a=0==a?this.axisMatrix.multiply(this.motionMatrix).multiply(this.translateMatrix):this.axisMatrix.multiply(this.translateMatrix).multiply(this.motionMatrix),this.parent.getAccum().multiply(a)):this.translateMatrix.multiply(this.motionMatrix)};Bone.prototype.calculate=function(a){this.pt=this.getAccum().affine(0,0,0);a||this.joint.forEach(function(a){a.calculate(!1)})};
Bone.prototype.conv=function(a){a=this.skeleton.rotationMatrix.affine(a.x,a.y,a.z);var b=(a.z+2E3)/2E3;return(new Matrix([[b,0,0,0],[0,b,0,0],[0,0,b,0],[0,0,0,1]])).affine(a.x,a.y,a.z)};Bone.prototype.drawLine=function(a){var b=this.conv(this.parent.pt),d=this.conv(this.pt),c=this.skeleton.scale,e=d.x*c,f=-d.y*c,g=b.x*c,b=-b.y*c,c=e-g,h=f-b;this.cx=g+c/2;this.cy=b+h/2;this.cz=d.z;this.radian=Math.atan2(h,c);a.beginPath();a.moveTo(g,b);a.lineTo(e,f);a.stroke()};
Bone.prototype.draw=function(a){this.calculate();this.parent&&this.drawLine(a);this.joint.forEach(function(b){b.draw(a)})};
document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("loading"),b=[AudioMixer.INSTANCE,MotionManager.INSTANCE],d=["aachan.bvh","kashiyuka.bvh","nocchi.bvh"],c=$("#view"),e=$("#slider"),f=$("#nameFlip"),g=!1,h=new Field,k=0,m=0,l=0,p=function(a){if(a.type.match(/^mouse/))k=a.pageX,m=a.pageY;else if(a.originalEvent.touches){var b=a.originalEvent.touches[0];k=b.pageX;m=b.pageY}l=a.which},q=function(a){var b,c;if(a.type.match(/^mouse/)){if(!l)return;b=a.pageX;c=a.pageY}else a.originalEvent.touches&&
(c=a.originalEvent.touches[0],b=c.pageX,c=c.pageY);a=m-c;h.rotateH(k-b);h.rotateV(a);k=b;m=c},n=function(a){l=0},r=function(){var a=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame,b=AudioMixer.INSTANCE.getCurrentTime();b&&(b=parseInt(b/.025),h.shiftMotion(b),g=!0,e.val(b),e.slider("refresh"),g=!1);h.draw();a(r)};c.mousedown(p);c.mousemove(q);c.mouseleave(n);c.mouseup(n);c.bind("touchstart",p);c.bind("touchmove",q);c.bind("touchend",
n);e.change(function(){if(!g){var a=e.val(),b=.025*a;h.shiftMotion(a);AudioMixer.INSTANCE.setCurrentTime(b)}});f.change(function(){h.showName=f.prop("checked")});$(window).resize(function(){var a=$("body"),b=$("#header"),c=$("#footer"),d=a.width(),a=a.height()-b.outerHeight(!0)-c.outerHeight(!0)-16;a/9<d/16?d=parseInt(a/9*16):a=parseInt(d/16*9);h.resetCanvas(d,a)});$(window).resize();$("#playButton").click(function(){if(AudioMixer.INSTANCE.getCurrentTime())AudioMixer.INSTANCE.fade();else{var a=h.getPanValue(),
b=e.val();AudioMixer.INSTANCE.play("Perfume_globalsite_sound",1,!0,a,.025*b)}});MotionManager.INSTANCE.reserve(d);AudioMixer.INSTANCE.reserve(["Perfume_globalsite_sound"]);var t=function(){var c=0,e=0,f=!0;b.forEach(function(a){c+=a.loaded;e+=a.max;f&=a.isComplete()});a.innerHTML=c+"/"+e;f?($.mobile.loading("hide"),a.parentNode.removeChild(a),r(),d.forEach(function(a){h.addMotion(a,MotionManager.INSTANCE.dic[a])})):setTimeout(t,100)};$.mobile.loading("show",{textVisible:!0});t()});
